-- WISHLIST 테스트 데이터 삽입
-- 인기순 테스트를 위한 찜 데이터 생성
-- POSTID 9~14에 대해 다양한 찜수 설정
-- USERID 3, 4, 5, 6, 7 사용

-- 확인: USER 테이블에 USERID 3, 4, 5, 6, 7이 있는지 확인
-- SELECT USERID, EMAIL, NAME FROM "USER" WHERE USERID IN (3, 4, 5, 6, 7) ORDER BY USERID;

-- 확인: PRODUCTPOST 테이블에 POSTID 9, 10, 11, 12, 13, 14가 있는지 확인
-- SELECT POSTID, POSTNAME FROM PRODUCTPOST WHERE POSTID IN (9, 10, 11, 12, 13, 14) ORDER BY POSTID;

-- 기존 WISHLIST 데이터 삭제 (중복 방지)
DELETE FROM WISHLIST;

-- 게시물 9번 (POSTID 9, gdgdgdgd) - 가장 인기: 5명이 찜
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 3, 9, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 4, 9, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 5, 9, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 6, 9, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 7, 9, SYSTIMESTAMP);

-- 게시물 10번 (POSTID 10, dgdsgdsdsfds) - 중간 인기: 3명이 찜
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 3, 10, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 4, 10, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 5, 10, SYSTIMESTAMP);

-- 게시물 11번 (POSTID 11, 신발OLOLOLOLL...) - 높은 인기: 4명이 찜
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 3, 11, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 4, 11, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 6, 11, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 7, 11, SYSTIMESTAMP);

-- 게시물 12번 (POSTID 12, 바지11111111111111...) - 낮은 인기: 2명이 찜
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 3, 12, SYSTIMESTAMP);
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 5, 12, SYSTIMESTAMP);

-- 게시물 13번 (POSTID 13, 바지22222222222222) - 매우 낮은 인기: 1명만 찜
INSERT INTO WISHLIST (WISHLISTID, USERID, POSTID, CREATEDAT) VALUES (SEQ_WISHLIST_WISHLISTID.NEXTVAL, 4, 13, SYSTIMESTAMP);

-- 게시물 14번 (POSTID 14, 바지33333333333333) - 찜 없음: 0명 (인기순에서 가장 낮음)

-- 찜수 확인 쿼리 (인기순 정렬 테스트)
SELECT 
    pp.POSTID,
    pp.POSTNAME,
    pp.BRAND,
    COUNT(w.WISHLISTID) as wishCount
FROM PRODUCTPOST pp
LEFT JOIN WISHLIST w ON pp.POSTID = w.POSTID
GROUP BY pp.POSTID, pp.POSTNAME, pp.BRAND
ORDER BY wishCount DESC, pp.CREATEDAT DESC;
