-- ============================================
-- 단성사 쇼핑몰 Oracle DB 스키마 생성 스크립트
-- ============================================

-- ============================================
-- 1. 시퀀스 생성
-- ============================================

-- 회원 시퀀스
CREATE SEQUENCE SEQ_USER_USERID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 상품게시물 시퀀스
CREATE SEQUENCE SEQ_PRODUCTPOST_POSTID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 상품 시퀀스
CREATE SEQUENCE SEQ_PRODUCT_PRODUCTID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 상품이미지 시퀀스
CREATE SEQUENCE SEQ_PRODUCTIMAGE_IMAGEID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 장바구니 시퀀스
CREATE SEQUENCE SEQ_CART_CARTID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 찜 시퀀스
CREATE SEQUENCE SEQ_WISHLIST_WISHLISTID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 주문 시퀀스
CREATE SEQUENCE SEQ_ORDER_ORDERID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 주문상세 시퀀스
CREATE SEQUENCE SEQ_ORDERITEM_ORDERITEMID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 결제 시퀀스
CREATE SEQUENCE SEQ_PAYMENT_PAYMENTID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 계좌 시퀀스
CREATE SEQUENCE SEQ_ACCOUNT_ACCOUNTID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 리뷰 시퀀스
CREATE SEQUENCE SEQ_REVIEW_REVIEWID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 리뷰이미지 시퀀스
CREATE SEQUENCE SEQ_REVIEWIMAGE_REVIEWIMAGEID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 환불/교환 시퀀스
CREATE SEQUENCE SEQ_REFUND_REFUNDID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================
-- 2. 테이블 생성
-- ============================================

-- 회원(User)
CREATE TABLE "USER" (
    USERID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(500),
    ISSELLER NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISSELLER IN (0, 1)),
    BUSINESSNUMBER VARCHAR2(20),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE "USER" IS '회원 테이블';
COMMENT ON COLUMN "USER".USERID IS '회원고유ID';
COMMENT ON COLUMN "USER".EMAIL IS '로그인이메일';
COMMENT ON COLUMN "USER".PASSWORD IS '비밀번호';
COMMENT ON COLUMN "USER".NAME IS '이름';
COMMENT ON COLUMN "USER".PHONE IS '전화번호';
COMMENT ON COLUMN "USER".ADDRESS IS '주소';
COMMENT ON COLUMN "USER".ISSELLER IS '사업자인지 일반회원인지 구분 (0:일반, 1:사업자)';
COMMENT ON COLUMN "USER".BUSINESSNUMBER IS '사업자등록번호';
COMMENT ON COLUMN "USER".CREATEDAT IS '회원가입날짜';
COMMENT ON COLUMN "USER".UPDATEDAT IS '회원정보수정날짜';

-- 상품게시물(ProductPost)
CREATE TABLE PRODUCTPOST (
    POSTID NUMBER PRIMARY KEY,
    SELLERID NUMBER NOT NULL,
    CATEGORYNAME VARCHAR2(100) NOT NULL,
    POSTNAME VARCHAR2(200) NOT NULL,
    DESCRIPTION CLOB,
    BRAND VARCHAR2(100),
    MATERIAL VARCHAR2(100),
    VIEWCOUNT NUMBER DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(20),
    GENDER VARCHAR2(10),
    SEASON VARCHAR2(20),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUCTPOST_SELLERID FOREIGN KEY (SELLERID) REFERENCES "USER"(USERID)
);

COMMENT ON TABLE PRODUCTPOST IS '상품게시물 테이블';
COMMENT ON COLUMN PRODUCTPOST.POSTID IS '게시물고유ID';
COMMENT ON COLUMN PRODUCTPOST.SELLERID IS '판매자ID (FK -> User)';
COMMENT ON COLUMN PRODUCTPOST.CATEGORYNAME IS '카테고리명 (예: "신발 스니커즈", "상의 맨투맨")';
COMMENT ON COLUMN PRODUCTPOST.POSTNAME IS '게시물명 (예: "나이키 에어맥스 신발")';
COMMENT ON COLUMN PRODUCTPOST.DESCRIPTION IS '상품 설명';
COMMENT ON COLUMN PRODUCTPOST.BRAND IS '브랜드 (예: "나이키", "아디다스", "퓨마" 등)';
COMMENT ON COLUMN PRODUCTPOST.MATERIAL IS '주요소재 (예: "면", "폴리에스터", "나일론" 등)';
COMMENT ON COLUMN PRODUCTPOST.VIEWCOUNT IS '조회수';
COMMENT ON COLUMN PRODUCTPOST.STATUS IS '게시물상태 (SELLING, SOLD_OUT)';
COMMENT ON COLUMN PRODUCTPOST.GENDER IS '성별 (MEN, WOMEN, UNISEX)';
COMMENT ON COLUMN PRODUCTPOST.SEASON IS '계절 (SPRING, SUMMER, FALL, WINTER, ALL_SEASON)';
COMMENT ON COLUMN PRODUCTPOST.CREATEDAT IS '게시물올린날짜';
COMMENT ON COLUMN PRODUCTPOST.UPDATEDAT IS '게시물수정한날짜';

-- 상품(Product)
CREATE TABLE PRODUCT (
    PRODUCTID NUMBER PRIMARY KEY,
    POSTID NUMBER NOT NULL,
    COLOR VARCHAR2(50) NOT NULL,
    PRODUCTSIZE VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL,
    DISCOUNTPRICE NUMBER,
    STOCK NUMBER DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(20),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUCT_POSTID FOREIGN KEY (POSTID) REFERENCES PRODUCTPOST(POSTID)
);

COMMENT ON TABLE PRODUCT IS '상품 테이블';
COMMENT ON COLUMN PRODUCT.PRODUCTID IS '상품고유ID';
COMMENT ON COLUMN PRODUCT.POSTID IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN PRODUCT.COLOR IS '컬러 (black, white, navy, gray, red 등)';
COMMENT ON COLUMN PRODUCT.PRODUCTSIZE IS '사이즈 (S, M, L, XL, FREE, 250, 260 등)';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.DISCOUNTPRICE IS '할인된가격';
COMMENT ON COLUMN PRODUCT.STOCK IS '재고수량';
COMMENT ON COLUMN PRODUCT.STATUS IS '판매상태 (SELLING, SOLD_OUT)';
COMMENT ON COLUMN PRODUCT.CREATEDAT IS '상품등록날짜';
COMMENT ON COLUMN PRODUCT.UPDATEDAT IS '상품수정한날짜';

-- 상품이미지(ProductImage)
CREATE TABLE PRODUCTIMAGE (
    IMAGEID NUMBER PRIMARY KEY,
    POSTID NUMBER NOT NULL,
    IMAGEURL VARCHAR2(500) NOT NULL,
    ISMAIN NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISMAIN IN (0, 1)),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUCTIMAGE_POSTID FOREIGN KEY (POSTID) REFERENCES PRODUCTPOST(POSTID)
);

COMMENT ON TABLE PRODUCTIMAGE IS '상품이미지 테이블';
COMMENT ON COLUMN PRODUCTIMAGE.IMAGEID IS '이미지ID';
COMMENT ON COLUMN PRODUCTIMAGE.POSTID IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN PRODUCTIMAGE.IMAGEURL IS '이미지경로';
COMMENT ON COLUMN PRODUCTIMAGE.ISMAIN IS '대표이미지 여부 (0:일반, 1:대표)';
COMMENT ON COLUMN PRODUCTIMAGE.CREATEDAT IS '이미지 만들어진 날짜';

-- 장바구니(Cart)
CREATE TABLE CART (
    CARTID NUMBER PRIMARY KEY,
    USERID NUMBER NOT NULL,
    PRODUCTID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CART_USERID FOREIGN KEY (USERID) REFERENCES "USER"(USERID),
    CONSTRAINT FK_CART_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

COMMENT ON TABLE CART IS '장바구니 테이블';
COMMENT ON COLUMN CART.CARTID IS '장바구니ID';
COMMENT ON COLUMN CART.USERID IS '유저ID (FK -> User)';
COMMENT ON COLUMN CART.PRODUCTID IS '상품ID (FK -> Product)';
COMMENT ON COLUMN CART.QUANTITY IS '해당상품수량';
COMMENT ON COLUMN CART.CREATEDAT IS '장바구니에추가된날짜';

-- 찜(Wishlist)
CREATE TABLE WISHLIST (
    WISHLISTID NUMBER PRIMARY KEY,
    USERID NUMBER NOT NULL,
    PRODUCTID NUMBER NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_WISHLIST_USERID FOREIGN KEY (USERID) REFERENCES "USER"(USERID),
    CONSTRAINT FK_WISHLIST_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

COMMENT ON TABLE WISHLIST IS '찜 테이블';
COMMENT ON COLUMN WISHLIST.WISHLISTID IS '찜ID';
COMMENT ON COLUMN WISHLIST.USERID IS '유저ID (FK -> User)';
COMMENT ON COLUMN WISHLIST.PRODUCTID IS '상품ID (FK -> Product)';
COMMENT ON COLUMN WISHLIST.CREATEDAT IS '찜목록에추가된날짜';

-- 주문(Order)
CREATE TABLE "ORDER" (
    ORDERID NUMBER PRIMARY KEY,
    USERID NUMBER NOT NULL,
    ORDERNUMBER VARCHAR2(50) NOT NULL UNIQUE,
    TOTALPRICE NUMBER NOT NULL,
    DISCOUNTAMOUNT NUMBER DEFAULT 0 NOT NULL,
    DELIVERYFEE NUMBER DEFAULT 0 NOT NULL,
    FINALPRICE NUMBER NOT NULL,
    ORDERSTATUS VARCHAR2(20),
    RECIPIENTNAME VARCHAR2(50) NOT NULL,
    RECIPIENTPHONE VARCHAR2(20) NOT NULL,
    ZIPCODE VARCHAR2(10),
    ADDRESS VARCHAR2(500) NOT NULL,
    DETAILADDRESS VARCHAR2(200),
    DELIVERYMEMO VARCHAR2(200),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDER_USERID FOREIGN KEY (USERID) REFERENCES "USER"(USERID)
);

COMMENT ON TABLE "ORDER" IS '주문 테이블';
COMMENT ON COLUMN "ORDER".ORDERID IS '주문ID';
COMMENT ON COLUMN "ORDER".USERID IS '유저ID (FK -> User)';
COMMENT ON COLUMN "ORDER".ORDERNUMBER IS '주문번호 (예: ORD20250114-001)';
COMMENT ON COLUMN "ORDER".TOTALPRICE IS '상품 총액';
COMMENT ON COLUMN "ORDER".DISCOUNTAMOUNT IS '할인된 금액';
COMMENT ON COLUMN "ORDER".DELIVERYFEE IS '배송비';
COMMENT ON COLUMN "ORDER".FINALPRICE IS '최종 결제금액';
COMMENT ON COLUMN "ORDER".ORDERSTATUS IS '주문상태 (CONFIRMED, PAID, DELIVERED, CANCELLED)';
COMMENT ON COLUMN "ORDER".RECIPIENTNAME IS '받는 분 이름';
COMMENT ON COLUMN "ORDER".RECIPIENTPHONE IS '받는 분 전화번호';
COMMENT ON COLUMN "ORDER".ZIPCODE IS '우편번호 (다음 주소검색 API 사용)';
COMMENT ON COLUMN "ORDER".ADDRESS IS '주소 (다음 주소검색 API에서 받은 기본 주소)';
COMMENT ON COLUMN "ORDER".DETAILADDRESS IS '상세 주소 (사용자가 직접 입력)';
COMMENT ON COLUMN "ORDER".DELIVERYMEMO IS '배송 메모 (문 앞, 경비실 등)';
COMMENT ON COLUMN "ORDER".CREATEDAT IS '주문된 날짜';
COMMENT ON COLUMN "ORDER".UPDATEDAT IS '주문이 수정된 날짜';

-- 주문상세(OrderItem)
CREATE TABLE ORDERITEM (
    ORDERITEMID NUMBER PRIMARY KEY,
    ORDERID NUMBER NOT NULL,
    PRODUCTID NUMBER NOT NULL,
    POSTID NUMBER NOT NULL,
    SELLERID NUMBER NOT NULL,
    POSTNAME VARCHAR2(200),
    COLOR VARCHAR2(50),
    PRODUCTSIZE VARCHAR2(20),
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    STATUS VARCHAR2(20),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDERITEM_ORDERID FOREIGN KEY (ORDERID) REFERENCES "ORDER"(ORDERID),
    CONSTRAINT FK_ORDERITEM_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID),
    CONSTRAINT FK_ORDERITEM_POSTID FOREIGN KEY (POSTID) REFERENCES PRODUCTPOST(POSTID),
    CONSTRAINT FK_ORDERITEM_SELLERID FOREIGN KEY (SELLERID) REFERENCES "USER"(USERID)
);

COMMENT ON TABLE ORDERITEM IS '주문상세 테이블';
COMMENT ON COLUMN ORDERITEM.ORDERITEMID IS '주문상세ID';
COMMENT ON COLUMN ORDERITEM.ORDERID IS '주문ID (FK -> Order)';
COMMENT ON COLUMN ORDERITEM.PRODUCTID IS '상품ID (FK -> Product)';
COMMENT ON COLUMN ORDERITEM.POSTID IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN ORDERITEM.SELLERID IS '판매자ID (FK -> User)';
COMMENT ON COLUMN ORDERITEM.POSTNAME IS '주문 당시 게시물명';
COMMENT ON COLUMN ORDERITEM.COLOR IS '주문 당시 색상';
COMMENT ON COLUMN ORDERITEM.PRODUCTSIZE IS '주문 당시 사이즈';
COMMENT ON COLUMN ORDERITEM.QUANTITY IS '수량';
COMMENT ON COLUMN ORDERITEM.PRICE IS '주문 당시 수량과 상품가격을 곱한 가격';
COMMENT ON COLUMN ORDERITEM.STATUS IS '상태 (CONFIRMED, CANCELLED, REFUNDED)';
COMMENT ON COLUMN ORDERITEM.CREATEDAT IS '주문된 날짜';

-- 계좌(Account)
CREATE TABLE ACCOUNT (
    ACCOUNTID NUMBER PRIMARY KEY,
    USERID NUMBER NOT NULL,
    BANKNAME VARCHAR2(50) NOT NULL,
    ACCOUNTNUMBER VARCHAR2(50) NOT NULL,
    ACCOUNTHOLDER VARCHAR2(50) NOT NULL,
    BALANCE NUMBER DEFAULT 0 NOT NULL,
    ISDEFAULT NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISDEFAULT IN (0, 1)),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ACCOUNT_USERID FOREIGN KEY (USERID) REFERENCES "USER"(USERID)
);

COMMENT ON TABLE ACCOUNT IS '계좌 테이블';
COMMENT ON COLUMN ACCOUNT.ACCOUNTID IS '계좌고유ID';
COMMENT ON COLUMN ACCOUNT.USERID IS '유저ID (FK -> User)';
COMMENT ON COLUMN ACCOUNT.BANKNAME IS '은행이름';
COMMENT ON COLUMN ACCOUNT.ACCOUNTNUMBER IS '계좌번호';
COMMENT ON COLUMN ACCOUNT.ACCOUNTHOLDER IS '통장에 적힌 이름';
COMMENT ON COLUMN ACCOUNT.BALANCE IS '잔액';
COMMENT ON COLUMN ACCOUNT.ISDEFAULT IS '기본계좌 여부 (0:일반, 1:기본)';
COMMENT ON COLUMN ACCOUNT.CREATEDAT IS '계좌등록날짜';

-- 결제(Payment)
CREATE TABLE PAYMENT (
    PAYMENTID NUMBER PRIMARY KEY,
    ORDERID NUMBER NOT NULL,
    ACCOUNTID NUMBER,
    PAYMENTMETHOD VARCHAR2(20),
    AMOUNT NUMBER NOT NULL,
    STATUS VARCHAR2(20),
    TRANSACTIONID VARCHAR2(100),
    PAIDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PAYMENT_ORDERID FOREIGN KEY (ORDERID) REFERENCES "ORDER"(ORDERID),
    CONSTRAINT FK_PAYMENT_ACCOUNTID FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
);

COMMENT ON TABLE PAYMENT IS '결제 테이블';
COMMENT ON COLUMN PAYMENT.PAYMENTID IS '결제고유ID';
COMMENT ON COLUMN PAYMENT.ORDERID IS '주문ID (FK -> Order)';
COMMENT ON COLUMN PAYMENT.ACCOUNTID IS '계좌ID (FK -> Account, nullable)';
COMMENT ON COLUMN PAYMENT.PAYMENTMETHOD IS '결제수단 (CARD, ACCOUNT, TOSS)';
COMMENT ON COLUMN PAYMENT.AMOUNT IS '결제금액';
COMMENT ON COLUMN PAYMENT.STATUS IS '결제상태 (COMPLETED, FAILED, CANCELLED)';
COMMENT ON COLUMN PAYMENT.TRANSACTIONID IS 'PG사 거래번호';
COMMENT ON COLUMN PAYMENT.PAIDAT IS '결제된 날짜';

-- 리뷰(Review)
CREATE TABLE REVIEW (
    REVIEWID NUMBER PRIMARY KEY,
    POSTID NUMBER NOT NULL,
    PRODUCTID NUMBER,
    USERID NUMBER NOT NULL,
    ORDERITEMID NUMBER NOT NULL,
    RATING NUMBER NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    CONTENT CLOB,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REVIEW_POSTID FOREIGN KEY (POSTID) REFERENCES PRODUCTPOST(POSTID),
    CONSTRAINT FK_REVIEW_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(PRODUCTID),
    CONSTRAINT FK_REVIEW_USERID FOREIGN KEY (USERID) REFERENCES "USER"(USERID),
    CONSTRAINT FK_REVIEW_ORDERITEMID FOREIGN KEY (ORDERITEMID) REFERENCES ORDERITEM(ORDERITEMID)
);

COMMENT ON TABLE REVIEW IS '리뷰 테이블';
COMMENT ON COLUMN REVIEW.REVIEWID IS '리뷰고유ID';
COMMENT ON COLUMN REVIEW.POSTID IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN REVIEW.PRODUCTID IS '상품ID (FK -> Product, nullable)';
COMMENT ON COLUMN REVIEW.USERID IS '유저ID (FK -> User)';
COMMENT ON COLUMN REVIEW.ORDERITEMID IS '주문상세ID (FK -> OrderItem)';
COMMENT ON COLUMN REVIEW.RATING IS '평점 (1~5점)';
COMMENT ON COLUMN REVIEW.CONTENT IS '리뷰텍스트';
COMMENT ON COLUMN REVIEW.CREATEDAT IS '글쓴날짜';
COMMENT ON COLUMN REVIEW.UPDATEDAT IS '수정한날짜';

-- 리뷰이미지(ReviewImage)
CREATE TABLE REVIEWIMAGE (
    REVIEWIMAGEID NUMBER PRIMARY KEY,
    REVIEWID NUMBER NOT NULL,
    IMAGEURL VARCHAR2(500) NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REVIEWIMAGE_REVIEWID FOREIGN KEY (REVIEWID) REFERENCES REVIEW(REVIEWID)
);

COMMENT ON TABLE REVIEWIMAGE IS '리뷰이미지 테이블';
COMMENT ON COLUMN REVIEWIMAGE.REVIEWIMAGEID IS '리뷰이미지ID';
COMMENT ON COLUMN REVIEWIMAGE.REVIEWID IS '리뷰ID (FK -> Review)';
COMMENT ON COLUMN REVIEWIMAGE.IMAGEURL IS '이미지경로';
COMMENT ON COLUMN REVIEWIMAGE.CREATEDAT IS '이미지 업로드 날짜';

-- 환불/교환(Refund)
CREATE TABLE REFUND (
    REFUNDID NUMBER PRIMARY KEY,
    ORDERITEMID NUMBER NOT NULL,
    USERID NUMBER NOT NULL,
    REFUNDTYPE VARCHAR2(20),
    REASON VARCHAR2(100) NOT NULL,
    REASONDETAIL CLOB,
    REFUNDAMOUNT NUMBER,
    ACCOUNTID NUMBER,
    STATUS VARCHAR2(20),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REFUND_ORDERITEMID FOREIGN KEY (ORDERITEMID) REFERENCES ORDERITEM(ORDERITEMID),
    CONSTRAINT FK_REFUND_USERID FOREIGN KEY (USERID) REFERENCES "USER"(USERID),
    CONSTRAINT FK_REFUND_ACCOUNTID FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
);

COMMENT ON TABLE REFUND IS '환불/교환 테이블';
COMMENT ON COLUMN REFUND.REFUNDID IS '환불/교환 고유ID';
COMMENT ON COLUMN REFUND.ORDERITEMID IS '주문상세ID (FK -> OrderItem)';
COMMENT ON COLUMN REFUND.USERID IS '유저ID (FK -> User)';
COMMENT ON COLUMN REFUND.REFUNDTYPE IS '환불/교환 유형 (REFUND, EXCHANGE)';
COMMENT ON COLUMN REFUND.REASON IS '이유 (선택식)';
COMMENT ON COLUMN REFUND.REASONDETAIL IS '이유를 텍스트로';
COMMENT ON COLUMN REFUND.REFUNDAMOUNT IS '환불하는 총가격';
COMMENT ON COLUMN REFUND.ACCOUNTID IS '환불받을 계좌 (FK -> Account, nullable)';
COMMENT ON COLUMN REFUND.STATUS IS '상태 (REQUESTED, APPROVED, COMPLETED)';
COMMENT ON COLUMN REFUND.CREATEDAT IS '환불/교환신청시간';

-- ============================================
-- 3. 인덱스 생성 (성능 최적화)
-- ============================================

-- 이메일 인덱스 (로그인 시 사용)
CREATE INDEX IDX_USER_EMAIL ON "USER"(EMAIL);

-- 판매자ID 인덱스 (상품게시물 조회 시 사용)
CREATE INDEX IDX_PRODUCTPOST_SELLERID ON PRODUCTPOST(SELLERID);

-- 게시물ID 인덱스 (상품 조회 시 사용)
CREATE INDEX IDX_PRODUCT_POSTID ON PRODUCT(POSTID);

-- 유저ID 인덱스 (장바구니, 찜 조회 시 사용)
CREATE INDEX IDX_CART_USERID ON CART(USERID);
CREATE INDEX IDX_WISHLIST_USERID ON WISHLIST(USERID);

-- 주문번호 인덱스 (주문 조회 시 사용)
CREATE INDEX IDX_ORDER_ORDERNUMBER ON "ORDER"(ORDERNUMBER);
CREATE INDEX IDX_ORDER_USERID ON "ORDER"(USERID);

-- 주문상세 인덱스
CREATE INDEX IDX_ORDERITEM_ORDERID ON ORDERITEM(ORDERID);
CREATE INDEX IDX_ORDERITEM_PRODUCTID ON ORDERITEM(PRODUCTID);

-- 리뷰 인덱스
CREATE INDEX IDX_REVIEW_POSTID ON REVIEW(POSTID);
CREATE INDEX IDX_REVIEW_USERID ON REVIEW(USERID);

-- 환불 인덱스
CREATE INDEX IDX_REFUND_USERID ON REFUND(USERID);
CREATE INDEX IDX_REFUND_ORDERITEMID ON REFUND(ORDERITEMID);

-- ============================================
-- 4. 트리거 생성 (시퀀스 자동 증가)
-- ============================================

-- 회원 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_USER_USERID
    BEFORE INSERT ON "USER"
    FOR EACH ROW
BEGIN
    IF :NEW.USERID IS NULL THEN
        :NEW.USERID := SEQ_USER_USERID.NEXTVAL;
    END IF;
END;
/

-- 상품게시물 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PRODUCTPOST_POSTID
    BEFORE INSERT ON PRODUCTPOST
    FOR EACH ROW
BEGIN
    IF :NEW.POSTID IS NULL THEN
        :NEW.POSTID := SEQ_PRODUCTPOST_POSTID.NEXTVAL;
    END IF;
END;
/

-- 상품 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PRODUCT_PRODUCTID
    BEFORE INSERT ON PRODUCT
    FOR EACH ROW
BEGIN
    IF :NEW.PRODUCTID IS NULL THEN
        :NEW.PRODUCTID := SEQ_PRODUCT_PRODUCTID.NEXTVAL;
    END IF;
END;
/

-- 상품이미지 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PRODUCTIMAGE_IMAGEID
    BEFORE INSERT ON PRODUCTIMAGE
    FOR EACH ROW
BEGIN
    IF :NEW.IMAGEID IS NULL THEN
        :NEW.IMAGEID := SEQ_PRODUCTIMAGE_IMAGEID.NEXTVAL;
    END IF;
END;
/

-- 장바구니 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_CART_CARTID
    BEFORE INSERT ON CART
    FOR EACH ROW
BEGIN
    IF :NEW.CARTID IS NULL THEN
        :NEW.CARTID := SEQ_CART_CARTID.NEXTVAL;
    END IF;
END;
/

-- 찜 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_WISHLIST_WISHLISTID
    BEFORE INSERT ON WISHLIST
    FOR EACH ROW
BEGIN
    IF :NEW.WISHLISTID IS NULL THEN
        :NEW.WISHLISTID := SEQ_WISHLIST_WISHLISTID.NEXTVAL;
    END IF;
END;
/

-- 주문 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_ORDER_ORDERID
    BEFORE INSERT ON "ORDER"
    FOR EACH ROW
BEGIN
    IF :NEW.ORDERID IS NULL THEN
        :NEW.ORDERID := SEQ_ORDER_ORDERID.NEXTVAL;
    END IF;
END;
/

-- 주문상세 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_ORDERITEM_ORDERITEMID
    BEFORE INSERT ON ORDERITEM
    FOR EACH ROW
BEGIN
    IF :NEW.ORDERITEMID IS NULL THEN
        :NEW.ORDERITEMID := SEQ_ORDERITEM_ORDERITEMID.NEXTVAL;
    END IF;
END;
/

-- 결제 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PAYMENT_PAYMENTID
    BEFORE INSERT ON PAYMENT
    FOR EACH ROW
BEGIN
    IF :NEW.PAYMENTID IS NULL THEN
        :NEW.PAYMENTID := SEQ_PAYMENT_PAYMENTID.NEXTVAL;
    END IF;
END;
/

-- 계좌 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_ACCOUNT_ACCOUNTID
    BEFORE INSERT ON ACCOUNT
    FOR EACH ROW
BEGIN
    IF :NEW.ACCOUNTID IS NULL THEN
        :NEW.ACCOUNTID := SEQ_ACCOUNT_ACCOUNTID.NEXTVAL;
    END IF;
END;
/

-- 리뷰 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_REVIEW_REVIEWID
    BEFORE INSERT ON REVIEW
    FOR EACH ROW
BEGIN
    IF :NEW.REVIEWID IS NULL THEN
        :NEW.REVIEWID := SEQ_REVIEW_REVIEWID.NEXTVAL;
    END IF;
END;
/

-- 리뷰이미지 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_REVIEWIMAGE_REVIEWIMAGEID
    BEFORE INSERT ON REVIEWIMAGE
    FOR EACH ROW
BEGIN
    IF :NEW.REVIEWIMAGEID IS NULL THEN
        :NEW.REVIEWIMAGEID := SEQ_REVIEWIMAGE_REVIEWIMAGEID.NEXTVAL;
    END IF;
END;
/

-- 환불/교환 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_REFUND_REFUNDID
    BEFORE INSERT ON REFUND
    FOR EACH ROW
BEGIN
    IF :NEW.REFUNDID IS NULL THEN
        :NEW.REFUNDID := SEQ_REFUND_REFUNDID.NEXTVAL;
    END IF;
END;
/

-- ============================================
-- 완료 메시지
-- ============================================
SELECT 'Oracle DB 스키마 생성이 완료되었습니다!' AS MESSAGE FROM DUAL;

