-- ============================================
-- 단성사 쇼핑몰 Oracle DB 스키마 생성 스크립트
-- ============================================

-- ============================================
-- 1. 시퀀스 생성
-- ============================================

-- 회원 시퀀스
CREATE SEQUENCE SEQ_USER_USERID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 카테고리 시퀀스
CREATE SEQUENCE SEQ_CATEGORY_CATEGORYID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 상품게시물 시퀀스
CREATE SEQUENCE SEQ_PRODUCTPOST_POSTID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 상품 시퀀스
CREATE SEQUENCE SEQ_PRODUCT_PRODUCTID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 상품이미지 시퀀스
CREATE SEQUENCE SEQ_PRODUCTIMAGE_IMAGEID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 장바구니 시퀀스
CREATE SEQUENCE SEQ_CART_CARTID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 찜 시퀀스
CREATE SEQUENCE SEQ_WISHLIST_WISHLISTID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 주문 시퀀스
CREATE SEQUENCE SEQ_ORDER_ORDERID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 주문상세 시퀀스
CREATE SEQUENCE SEQ_ORDERITEM_ORDERITEMID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 결제 시퀀스
CREATE SEQUENCE SEQ_PAYMENT_PAYMENTID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 계좌 시퀀스 제거됨 (ACCOUNT 테이블 미사용)

-- 리뷰 시퀀스
CREATE SEQUENCE SEQ_REVIEW_REVIEWID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 리뷰이미지 시퀀스
CREATE SEQUENCE SEQ_REVIEWIMAGE_REVIEWIMAGEID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 환불/교환 시퀀스
CREATE SEQUENCE SEQ_REFUND_REFUNDID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================
-- 2. 테이블 생성
-- ============================================

-- 회원(User)
CREATE TABLE "user" (
    USERID_SEQ NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20),
    ZIPCODE VARCHAR2(10),
    ISSELLER NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISSELLER IN (0, 1)),
    BN_NO VARCHAR2(20),
    BRAND VARCHAR2(100),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    D_ADDR VARCHAR2(200),
    ADDR VARCHAR2(500)
);

COMMENT ON TABLE "user" IS '회원 테이블';
COMMENT ON COLUMN "user".USERID_SEQ IS '회원고유ID';
COMMENT ON COLUMN "user".EMAIL IS '로그인이메일';
COMMENT ON COLUMN "user".PASSWORD IS '비밀번호 (BCrypt 암호화)';
COMMENT ON COLUMN "user".NAME IS '이름';
COMMENT ON COLUMN "user".PHONE IS '전화번호';
COMMENT ON COLUMN "user".ZIPCODE IS '우편번호 (다음 주소검색 API)';
COMMENT ON COLUMN "user".ISSELLER IS '사업자인지 일반회원인지 구분 (0:일반, 1:사업자)';
COMMENT ON COLUMN "user".BN_NO IS '사업자등록번호';
COMMENT ON COLUMN "user".BRAND IS '상호명 (판매자 전용)';
COMMENT ON COLUMN "user".CREATEDAT IS '회원가입날짜';
COMMENT ON COLUMN "user".UPDATEDAT IS '회원정보수정날짜';
COMMENT ON COLUMN "user".D_ADDR IS '상세 주소';
COMMENT ON COLUMN "user".ADDR IS '기본 주소';

-- 카테고리(Category)
CREATE TABLE CATEGORY (
    CATEGORYID_SEQ NUMBER PRIMARY KEY,
    MAIN_CATEGORY VARCHAR2(20) NOT NULL,
    MID_CATEGORY VARCHAR2(50) NOT NULL,
    SUB_CATEGORY VARCHAR2(50) NOT NULL,
    CATEGORYNAME VARCHAR2(100) NOT NULL,
    IMAGE_URL VARCHAR2(500),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_CATEGORY_NAME UNIQUE (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY)
);

COMMENT ON TABLE CATEGORY IS '카테고리 테이블';
COMMENT ON COLUMN CATEGORY.CATEGORYID_SEQ IS '카테고리 고유ID';
COMMENT ON COLUMN CATEGORY.MAIN_CATEGORY IS '대분류 (전체, 남성, 여성)';
COMMENT ON COLUMN CATEGORY.MID_CATEGORY IS '중분류 (신발, 상의, 아우터, 바지, 원피스/스커트, 가방, 패션소품)';
COMMENT ON COLUMN CATEGORY.SUB_CATEGORY IS '소분류 (스니커즈, 맨투맨, 후드 등)';
COMMENT ON COLUMN CATEGORY.CATEGORYNAME IS '카테고리 전체 경로 (예: "신발 스니커즈")';
COMMENT ON COLUMN CATEGORY.IMAGE_URL IS '카테고리 이미지 경로';
COMMENT ON COLUMN CATEGORY.CREATEDAT IS '카테고리 생성일시';

-- ============================================
-- 3. 카테고리 데이터 INSERT (categories.json 기반)
-- ============================================

-- 전체 > 신발
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '신발', '스니커즈', '신발 스니커즈', '/categoryImage/man-sneakers.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '신발', '구두', '신발 구두', '/categoryImage/man-dress_shoes.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '신발', '샌들/슬리퍼', '신발 샌들/슬리퍼', '/categoryImage/man-sandals.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '신발', '부츠/워커', '신발 부츠/워커', '/categoryImage/man-boots.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '신발', '스포츠화', '신발 스포츠화', '/categoryImage/unisex-sport.png');

-- 전체 > 상의
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '상의', '맨투맨', '상의 맨투맨', '/categoryImage/man-T-shirt.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '상의', '후드', '상의 후드', '/categoryImage/man-hoodie.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '상의', '셔츠', '상의 셔츠', '/categoryImage/man-shirt.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '상의', '긴소매', '상의 긴소매', '/categoryImage/man-longsleeve.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '상의', '반소매', '상의 반소매', '/categoryImage/man-short.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '상의', '니트', '상의 니트', '/categoryImage/man-knit.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '상의', '민소매', '상의 민소매', '/categoryImage/woman-sleeve.png');

-- 전체 > 아우터
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '숏패딩', '아우터 숏패딩', '/categoryImage/unisex-puffer.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '롱패딩', '아우터 롱패딩', '/categoryImage/man-longpuffer.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '무스탕', '아우터 무스탕', '/categoryImage/man-mouton.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '코트', '아우터 코트', '/categoryImage/man-coat.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '가디건', '아우터 가디건', '/categoryImage/man-cardigan.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '후드 집업', '아우터 후드 집업', '/categoryImage/man-hoodzipup.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '슈트', '아우터 슈트', '/categoryImage/man-dress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '아우터', '재킷', '아우터 재킷', '/categoryImage/man-jacket.png');

-- 전체 > 바지
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '바지', '데님', '바지 데님', '/categoryImage/man-denim.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '바지', '트레이닝', '바지 트레이닝', '/categoryImage/man-trainning.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '바지', '코튼', '바지 코튼', '/categoryImage/man-cotton.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '바지', '슬렉스', '바지 슬렉스', '/categoryImage/man-slacks.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '바지', '숏팬츠', '바지 숏팬츠', '/categoryImage/man-short.png');

-- 전체 > 원피스/스커트
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '원피스/스커트', '미니 원피스', '원피스/스커트 미니 원피스', '/categoryImage/woman-shortdress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '원피스/스커트', '미디 원피스', '원피스/스커트 미디 원피스', '/categoryImage/woman-middress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '원피스/스커트', '맥시 원피스', '원피스/스커트 맥시 원피스', '/categoryImage/woman-long dress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '원피스/스커트', '미니 스커트', '원피스/스커트 미니 스커트', '/categoryImage/woman-shortskrit.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '원피스/스커트', '미디 스커트', '원피스/스커트 미디 스커트', '/categoryImage/woman-mid.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '원피스/스커트', '맥시 스커트', '원피스/스커트 맥시 스커트', '/categoryImage/woman-long_skirt.png');

-- 전체 > 가방
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '가방', '백팩', '가방 백팩', '/categoryImage/man-backpack.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '가방', '크로스백', '가방 크로스백', '/categoryImage/man-cross.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '가방', '에코백', '가방 에코백', '/categoryImage/man-echo.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '가방', '파우치', '가방 파우치', '/categoryImage/man-pouch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '가방', '클러치백', '가방 클러치백', '/categoryImage/man-clutch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '가방', '토트백', '가방 토트백', '/categoryImage/woman-tote.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '가방', '숄더백', '가방 숄더백', '/categoryImage/woman-shoulder.png');

-- 전체 > 패션소품
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '패션소품', '모자', '패션소품 모자', '/categoryImage/unisex-cap.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '패션소품', '머플러', '패션소품 머플러', '/categoryImage/man-neck.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '패션소품', '악세사리', '패션소품 악세사리', '/categoryImage/man-accessory.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '패션소품', '양말', '패션소품 양말', '/categoryImage/man-socks.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '패션소품', '선글라스', '패션소품 선글라스', '/categoryImage/man-sunglasses.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '패션소품', '시계', '패션소품 시계', '/categoryImage/man-watch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('전체', '패션소품', '벨트', '패션소품 벨트', '/categoryImage/man-belt.png');

-- 남성 > 신발
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '신발', '스니커즈', '신발 스니커즈', '/categoryImage/man-sneakers.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '신발', '구두', '신발 구두', '/categoryImage/man-dress_shoes.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '신발', '샌들/슬리퍼', '신발 샌들/슬리퍼', '/categoryImage/man-sandals.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '신발', '부츠/워커', '신발 부츠/워커', '/categoryImage/man-boots.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '신발', '스포츠화', '신발 스포츠화', '/categoryImage/unisex-sport.png');

-- 남성 > 상의
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '상의', '맨투맨', '상의 맨투맨', '/categoryImage/man-T-shirt.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '상의', '후드', '상의 후드', '/categoryImage/man-hoodie.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '상의', '셔츠', '상의 셔츠', '/categoryImage/man-shirt.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '상의', '긴소매', '상의 긴소매', '/categoryImage/man-longsleeve.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '상의', '반소매', '상의 반소매', '/categoryImage/man-short.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '상의', '니트', '상의 니트', '/categoryImage/man-knit.png');

-- 남성 > 아우터
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '숏패딩', '아우터 숏패딩', '/categoryImage/unisex-puffer.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '롱패딩', '아우터 롱패딩', '/categoryImage/man-longpuffer.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '무스탕', '아우터 무스탕', '/categoryImage/man-mouton.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '코트', '아우터 코트', '/categoryImage/man-coat.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '가디건', '아우터 가디건', '/categoryImage/man-cardigan.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '후드 집업', '아우터 후드 집업', '/categoryImage/man-hoodzipup.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '슈트', '아우터 슈트', '/categoryImage/man-dress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '아우터', '재킷', '아우터 재킷', '/categoryImage/man-jacket.png');

-- 남성 > 바지
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '바지', '데님', '바지 데님', '/categoryImage/man-denim.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '바지', '트레이닝', '바지 트레이닝', '/categoryImage/man-trainning.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '바지', '코튼', '바지 코튼', '/categoryImage/man-cotton.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '바지', '슬렉스', '바지 슬렉스', '/categoryImage/man-slacks.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '바지', '숏팬츠', '바지 숏팬츠', '/categoryImage/man-short.png');

-- 남성 > 가방
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '가방', '백팩', '가방 백팩', '/categoryImage/man-backpack.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '가방', '크로스백', '가방 크로스백', '/categoryImage/man-cross.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '가방', '에코백', '가방 에코백', '/categoryImage/man-echo.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '가방', '파우치', '가방 파우치', '/categoryImage/man-pouch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '가방', '클러치백', '가방 클러치백', '/categoryImage/man-clutch.png');

-- 남성 > 패션소품
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '패션소품', '모자', '패션소품 모자', '/categoryImage/unisex-cap.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '패션소품', '머플러', '패션소품 머플러', '/categoryImage/man-neck.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '패션소품', '악세사리', '패션소품 악세사리', '/categoryImage/man-accessory.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '패션소품', '양말', '패션소품 양말', '/categoryImage/man-socks.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '패션소품', '선글라스', '패션소품 선글라스', '/categoryImage/man-sunglasses.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '패션소품', '시계', '패션소품 시계', '/categoryImage/man-watch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('남성', '패션소품', '벨트', '패션소품 벨트', '/categoryImage/man-belt.png');

-- 여성 > 신발
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '신발', '스니커즈', '신발 스니커즈', '/categoryImage/man-sneakers.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '신발', '구두', '신발 구두', '/categoryImage/woman-dress-shoes.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '신발', '샌들/슬리퍼', '신발 샌들/슬리퍼', '/categoryImage/woman-sandals.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '신발', '부츠/워커', '신발 부츠/워커', '/categoryImage/wonman-boots.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '신발', '스포츠화', '신발 스포츠화', '/categoryImage/unisex-sport.png');

-- 여성 > 상의
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '상의', '맨투맨', '상의 맨투맨', '/categoryImage/woman-T-shirt.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '상의', '후드', '상의 후드', '/categoryImage/woman-hoodie.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '상의', '셔츠', '상의 셔츠', '/categoryImage/woman-shirts.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '상의', '긴소매', '상의 긴소매', '/categoryImage/woman-longsleeve.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '상의', '반소매', '상의 반소매', '/categoryImage/woman-short.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '상의', '니트', '상의 니트', '/categoryImage/woman-knit.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '상의', '민소매', '상의 민소매', '/categoryImage/woman-sleeve.png');

-- 여성 > 아우터
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '숏패딩', '아우터 숏패딩', '/categoryImage/unisex-puffer.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '롱패딩', '아우터 롱패딩', '/categoryImage/woman-long_puffer.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '무스탕', '아우터 무스탕', '/categoryImage/woman-mouton.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '코트', '아우터 코트', '/categoryImage/wonman-coat.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '가디건', '아우터 가디건', '/categoryImage/woman-cardigan.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '후드 집업', '아우터 후드 집업', '/categoryImage/wonman-hoodzipup.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '슈트', '아우터 슈트', '/categoryImage/woman-middress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '아우터', '재킷', '아우터 재킷', '/categoryImage/woman-jacket.png');

-- 여성 > 바지
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '바지', '데님', '바지 데님', '/categoryImage/woman-denim.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '바지', '트레이닝', '바지 트레이닝', '/categoryImage/wonman-training.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '바지', '코튼', '바지 코튼', '/categoryImage/woman-cotton.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '바지', '슬렉스', '바지 슬렉스', '/categoryImage/woman-slacks.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '바지', '숏팬츠', '바지 숏팬츠', '/categoryImage/woman-short.png');

-- 여성 > 원피스/스커트
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '원피스/스커트', '미니 원피스', '원피스/스커트 미니 원피스', '/categoryImage/woman-shortdress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '원피스/스커트', '미디 원피스', '원피스/스커트 미디 원피스', '/categoryImage/woman-middress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '원피스/스커트', '맥시 원피스', '원피스/스커트 맥시 원피스', '/categoryImage/woman-long dress.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '원피스/스커트', '미니 스커트', '원피스/스커트 미니 스커트', '/categoryImage/woman-shortskrit.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '원피스/스커트', '미디 스커트', '원피스/스커트 미디 스커트', '/categoryImage/woman-mid.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '원피스/스커트', '맥시 스커트', '원피스/스커트 맥시 스커트', '/categoryImage/woman-long_skirt.png');

-- 여성 > 가방
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '가방', '백팩', '가방 백팩', '/categoryImage/woman-backpack.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '가방', '크로스백', '가방 크로스백', '/categoryImage/woman_cross.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '가방', '에코백', '가방 에코백', '/categoryImage/woman-echo.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '가방', '파우치', '가방 파우치', '/categoryImage/woman-pouch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '가방', '클러치백', '가방 클러치백', '/categoryImage/woman-clutch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '가방', '토트백', '가방 토트백', '/categoryImage/woman-tote.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '가방', '숄더백', '가방 숄더백', '/categoryImage/woman-shoulder.png');

-- 여성 > 패션소품
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '패션소품', '모자', '패션소품 모자', '/categoryImage/unisex-cap.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '패션소품', '머플러', '패션소품 머플러', 'https://via.placeholder.com/150x150/000000/FFFFFF?text=SCARF');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '패션소품', '악세사리', '패션소품 악세사리', '/categoryImage/woman-accessory.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '패션소품', '양말', '패션소품 양말', '/categoryImage/woman-socks.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '패션소품', '선글라스', '패션소품 선글라스', '/categoryImage/woman-sunglasses.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '패션소품', '시계', '패션소품 시계', '/categoryImage/woman-watch.png');
INSERT INTO CATEGORY (MAIN_CATEGORY, MID_CATEGORY, SUB_CATEGORY, CATEGORYNAME, IMAGE_URL) VALUES ('여성', '패션소품', '벨트', '패션소품 벨트', '/categoryImage/woman-belt.png');

-- 상품게시물(ProductPost)
CREATE TABLE PRODUCTPOST (
    POSTID_SEQ NUMBER PRIMARY KEY,
    USERID_SEQ NUMBER NOT NULL,
    CATEGORYID_SEQ NUMBER NOT NULL,
    POSTNAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    BRAND VARCHAR2(100),
    MATERIAL VARCHAR2(100),
    VIEWCOUNT NUMBER DEFAULT 0 NOT NULL,
    WISHCOUNT NUMBER DEFAULT 0 NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (STATUS IN (0, 1)),
    GENDER VARCHAR2(1),
    SEASON VARCHAR2(3),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUCTPOST_USERID_SEQ FOREIGN KEY (USERID_SEQ) REFERENCES "user"(USERID_SEQ),
    CONSTRAINT FK_PRODUCTPOST_CATEGORYID_SEQ FOREIGN KEY (CATEGORYID_SEQ) REFERENCES CATEGORY(CATEGORYID_SEQ)
);

COMMENT ON TABLE PRODUCTPOST IS '상품게시물 테이블';
COMMENT ON COLUMN PRODUCTPOST.POSTID_SEQ IS '게시물고유ID';
COMMENT ON COLUMN PRODUCTPOST.USERID_SEQ IS '판매자ID (FK -> User)';
COMMENT ON COLUMN PRODUCTPOST.CATEGORYID_SEQ IS '카테고리ID (FK -> Category)';
COMMENT ON COLUMN PRODUCTPOST.POSTNAME IS '게시물명 (예: "나이키 에어맥스 신발")';
COMMENT ON COLUMN PRODUCTPOST.DESCRIPTION IS '상품 설명';
COMMENT ON COLUMN PRODUCTPOST.BRAND IS '브랜드 (예: "나이키", "아디다스", "퓨마" 등)';
COMMENT ON COLUMN PRODUCTPOST.MATERIAL IS '주요소재 (예: "면", "폴리에스터", "나일론" 등)';
COMMENT ON COLUMN PRODUCTPOST.VIEWCOUNT IS '조회수';
COMMENT ON COLUMN PRODUCTPOST.WISHCOUNT IS '찜수 (WISHLIST 테이블 트리거로 자동 업데이트)';
COMMENT ON COLUMN PRODUCTPOST.STATUS IS '게시물상태 (1=SELLING 판매중, 0=SOLD_OUT 품절)';
COMMENT ON COLUMN PRODUCTPOST.GENDER IS '성별 (M=MEN 남성, W=WOMEN 여성, U=UNISEX 공용)';
COMMENT ON COLUMN PRODUCTPOST.SEASON IS '계절 (SPR=봄, SMR=여름, FAL=가을, WTR=겨울, ALL=사계절)';
COMMENT ON COLUMN PRODUCTPOST.CREATEDAT IS '게시물올린날짜';
COMMENT ON COLUMN PRODUCTPOST.UPDATEDAT IS '게시물수정한날짜';

-- 상품(Product)
CREATE TABLE PRODUCT (
    PRODUCTID_SEQ NUMBER PRIMARY KEY,
    POSTID_SEQ NUMBER NOT NULL,
    COLOR VARCHAR2(50) NOT NULL,
    PRODUCTSIZE VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL,
    DISCOUNTPRICE NUMBER,
    STOCK NUMBER DEFAULT 0 NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (STATUS IN (0, 1)),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUCT_POSTID_SEQ FOREIGN KEY (POSTID_SEQ) REFERENCES PRODUCTPOST(POSTID_SEQ)
);

COMMENT ON TABLE PRODUCT IS '상품 테이블';
COMMENT ON COLUMN PRODUCT.PRODUCTID_SEQ IS '상품고유ID';
COMMENT ON COLUMN PRODUCT.POSTID_SEQ IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN PRODUCT.COLOR IS '컬러 (black, white, navy, gray, red 등)';
COMMENT ON COLUMN PRODUCT.PRODUCTSIZE IS '사이즈 (S, M, L, XL, FREE, 250, 260 등)';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.DISCOUNTPRICE IS '할인된가격';
COMMENT ON COLUMN PRODUCT.STOCK IS '재고수량';
COMMENT ON COLUMN PRODUCT.STATUS IS '판매상태 (1=SELLING 판매중, 0=SOLD_OUT 품절)';
COMMENT ON COLUMN PRODUCT.CREATEDAT IS '상품등록날짜';
COMMENT ON COLUMN PRODUCT.UPDATEDAT IS '상품수정한날짜';

-- 상품이미지(ProductImage)
CREATE TABLE PRODUCTIMAGE (
    IMAGEID_SEQ NUMBER PRIMARY KEY,
    POSTID_SEQ NUMBER NOT NULL,
    IMAGEURL VARCHAR2(500) NOT NULL,
    ISMAIN NUMBER(1) DEFAULT 0 NOT NULL CHECK (ISMAIN IN (0, 1)),
    IMAGETYPE VARCHAR2(20),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUCTIMAGE_POSTID_SEQ FOREIGN KEY (POSTID_SEQ) REFERENCES PRODUCTPOST(POSTID_SEQ)
);

COMMENT ON TABLE PRODUCTIMAGE IS '상품이미지 테이블';
COMMENT ON COLUMN PRODUCTIMAGE.IMAGEID_SEQ IS '이미지ID';
COMMENT ON COLUMN PRODUCTIMAGE.POSTID_SEQ IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN PRODUCTIMAGE.IMAGEURL IS '이미지경로';
COMMENT ON COLUMN PRODUCTIMAGE.ISMAIN IS '대표이미지 여부 (0:일반, 1:대표)';
COMMENT ON COLUMN PRODUCTIMAGE.IMAGETYPE IS '이미지 타입 (GALLERY: 갤러리 이미지, DESCRIPTION: 상품 설명 이미지)';
COMMENT ON COLUMN PRODUCTIMAGE.CREATEDAT IS '이미지 만들어진 날짜';

-- 장바구니(Cart)
CREATE TABLE CART (
    CARTID_SEQ NUMBER PRIMARY KEY,
    USERID_SEQ NUMBER NOT NULL,
    PRODUCTID_SEQ NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CART_USERID_SEQ FOREIGN KEY (USERID_SEQ) REFERENCES "user"(USERID_SEQ),
    CONSTRAINT FK_CART_PRODUCTID_SEQ FOREIGN KEY (PRODUCTID_SEQ) REFERENCES PRODUCT(PRODUCTID_SEQ)
);

COMMENT ON TABLE CART IS '장바구니 테이블';
COMMENT ON COLUMN CART.CARTID_SEQ IS '장바구니ID';
COMMENT ON COLUMN CART.USERID_SEQ IS '유저ID (FK -> User)';
COMMENT ON COLUMN CART.PRODUCTID_SEQ IS '상품ID (FK -> Product)';
COMMENT ON COLUMN CART.QUANTITY IS '해당상품수량';
COMMENT ON COLUMN CART.CREATEDAT IS '장바구니에추가된날짜';

-- 찜(Wishlist)
CREATE TABLE WISHLIST (
    WISHLISTID_SEQ NUMBER PRIMARY KEY,
    USERID_SEQ NUMBER NOT NULL,
    POSTID_SEQ NUMBER NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_WISHLIST_USERID_SEQ FOREIGN KEY (USERID_SEQ) REFERENCES "user"(USERID_SEQ),
    CONSTRAINT FK_WISHLIST_POSTID_SEQ FOREIGN KEY (POSTID_SEQ) REFERENCES PRODUCTPOST(POSTID_SEQ),
    CONSTRAINT UK_WISHLIST_USER_POST UNIQUE (USERID_SEQ, POSTID_SEQ)
);

COMMENT ON TABLE WISHLIST IS '찜 테이블';
COMMENT ON COLUMN WISHLIST.WISHLISTID_SEQ IS '찜ID';
COMMENT ON COLUMN WISHLIST.USERID_SEQ IS '유저ID (FK -> User)';
COMMENT ON COLUMN WISHLIST.POSTID_SEQ IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN WISHLIST.CREATEDAT IS '찜목록에추가된날짜';

-- 주문(Order)
CREATE TABLE "order" (
    ORDERID_SEQ NUMBER PRIMARY KEY,
    USERID_SEQ NUMBER NOT NULL,
    OD_NO VARCHAR2(50) NOT NULL UNIQUE,
    TOTALPRICE NUMBER NOT NULL,
    DISCOUNTAMOUNT NUMBER DEFAULT 0 NOT NULL,
    DV_FEE NUMBER DEFAULT 0 NOT NULL,
    FINALPRICE NUMBER NOT NULL,
    OD_STATUS VARCHAR2(20),
    RECIPIENTNAME VARCHAR2(50) NOT NULL,
    RECIPIENTPHONE VARCHAR2(20) NOT NULL,
    ZIPCODE VARCHAR2(10),
    ADDR VARCHAR2(500) NOT NULL,
    DETAILADDRESS VARCHAR2(200),
    DV_MEMO VARCHAR2(200),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDER_USERID_SEQ FOREIGN KEY (USERID_SEQ) REFERENCES "user"(USERID_SEQ)
);

COMMENT ON TABLE "order" IS '주문 테이블';
COMMENT ON COLUMN "order".ORDERID_SEQ IS '주문ID';
COMMENT ON COLUMN "order".USERID_SEQ IS '유저ID (FK -> User)';
COMMENT ON COLUMN "order".OD_NO IS '주문번호 (예: ORD20250114-001)';
COMMENT ON COLUMN "order".TOTALPRICE IS '상품 총액';
COMMENT ON COLUMN "order".DISCOUNTAMOUNT IS '할인된 금액';
COMMENT ON COLUMN "order".DV_FEE IS '배송비';
COMMENT ON COLUMN "order".FINALPRICE IS '최종 결제금액';
COMMENT ON COLUMN "order".OD_STATUS IS '주문상태 (CONFIRMED, PAID, DELIVERED, CANCELLED)';
COMMENT ON COLUMN "order".RECIPIENTNAME IS '받는 분 이름';
COMMENT ON COLUMN "order".RECIPIENTPHONE IS '받는 분 전화번호';
COMMENT ON COLUMN "order".ZIPCODE IS '우편번호 (다음 주소검색 API 사용)';
COMMENT ON COLUMN "order".ADDR IS '주소 (다음 주소검색 API에서 받은 기본 주소)';
COMMENT ON COLUMN "order".DETAILADDRESS IS '상세 주소 (사용자가 직접 입력)';
COMMENT ON COLUMN "order".DV_MEMO IS '배송 메모 (문 앞, 경비실 등)';
COMMENT ON COLUMN "order".CREATEDAT IS '주문된 날짜';
COMMENT ON COLUMN "order".UPDATEDAT IS '주문이 수정된 날짜';

-- 주문상세(OrderItem)
CREATE TABLE ORDERITEM (
    ORDERITEMID_SEQ NUMBER PRIMARY KEY,
    ORDERID_SEQ NUMBER NOT NULL,
    PRODUCTID_SEQ NUMBER NOT NULL,
    POSTID_SEQ NUMBER NOT NULL,
    USERID_SEQ NUMBER NOT NULL,
    POSTNAME VARCHAR2(200),
    COLOR VARCHAR2(50),
    PRODUCTSIZE VARCHAR2(20),
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    STATUS VARCHAR2(3),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDERITEM_ORDERID_SEQ FOREIGN KEY (ORDERID_SEQ) REFERENCES "order"(ORDERID_SEQ),
    CONSTRAINT FK_ORDERITEM_PRODUCTID_SEQ FOREIGN KEY (PRODUCTID_SEQ) REFERENCES PRODUCT(PRODUCTID_SEQ),
    CONSTRAINT FK_ORDERITEM_POSTID_SEQ FOREIGN KEY (POSTID_SEQ) REFERENCES PRODUCTPOST(POSTID_SEQ),
    CONSTRAINT FK_ORDERITEM_USERID_SEQ FOREIGN KEY (USERID_SEQ) REFERENCES "user"(USERID_SEQ)
);

COMMENT ON TABLE ORDERITEM IS '주문상세 테이블';
COMMENT ON COLUMN ORDERITEM.ORDERITEMID_SEQ IS '주문상세ID';
COMMENT ON COLUMN ORDERITEM.ORDERID_SEQ IS '주문ID (FK -> Order)';
COMMENT ON COLUMN ORDERITEM.PRODUCTID_SEQ IS '상품ID (FK -> Product)';
COMMENT ON COLUMN ORDERITEM.POSTID_SEQ IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN ORDERITEM.USERID_SEQ IS '판매자ID (FK -> User)';
COMMENT ON COLUMN ORDERITEM.POSTNAME IS '주문 당시 게시물명';
COMMENT ON COLUMN ORDERITEM.COLOR IS '주문 당시 색상';
COMMENT ON COLUMN ORDERITEM.PRODUCTSIZE IS '주문 당시 사이즈';
COMMENT ON COLUMN ORDERITEM.QUANTITY IS '수량';
COMMENT ON COLUMN ORDERITEM.PRICE IS '주문 당시 수량과 상품가격을 곱한 가격';
COMMENT ON COLUMN ORDERITEM.STATUS IS '상태 (con=CONFIRMED, can=CANCELLED, ref=REFUNDED)';
COMMENT ON COLUMN ORDERITEM.CREATEDAT IS '주문된 날짜';

-- 결제(Payment)
CREATE TABLE PAYMENT (
    PAYMENTID NUMBER PRIMARY KEY,
    ORDERID NUMBER NOT NULL,
    PAYMENTMETHOD VARCHAR2(20),
    AMOUNT NUMBER NOT NULL,
    STATUS VARCHAR2(20),
    TRANSACTIONID VARCHAR2(100),
    PAIDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PAYMENT_ORDERID FOREIGN KEY (ORDERID) REFERENCES "order"(ORDERID_SEQ)
);

COMMENT ON TABLE PAYMENT IS '결제 테이블';
COMMENT ON COLUMN PAYMENT.PAYMENTID IS '결제고유ID';
COMMENT ON COLUMN PAYMENT.ORDERID IS '주문ID (FK -> Order)';
COMMENT ON COLUMN PAYMENT.PAYMENTMETHOD IS '결제수단 (CARD, TOSS)';
COMMENT ON COLUMN PAYMENT.AMOUNT IS '결제금액';
COMMENT ON COLUMN PAYMENT.STATUS IS '결제상태 (COMPLETED, FAILED, CANCELLED)';
COMMENT ON COLUMN PAYMENT.TRANSACTIONID IS 'PG사 거래번호';
COMMENT ON COLUMN PAYMENT.PAIDAT IS '결제된 날짜';

-- 리뷰(Review)
CREATE TABLE REVIEW (
    REVIEWID_SEQ NUMBER PRIMARY KEY,
    POSTID_SEQ NUMBER NOT NULL,
    PRODUCTID_SEQ NUMBER,
    USERID_SEQ NUMBER NOT NULL,
    ORDERITEMID_SEQ NUMBER NOT NULL,
    RATING NUMBER NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    CONTENT CLOB,
    SELLERREPLY VARCHAR2(2000),
    SELLERREPLYAT TIMESTAMP,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REVIEW_POSTID_SEQ FOREIGN KEY (POSTID_SEQ) REFERENCES PRODUCTPOST(POSTID_SEQ),
    CONSTRAINT FK_REVIEW_PRODUCTID_SEQ FOREIGN KEY (PRODUCTID_SEQ) REFERENCES PRODUCT(PRODUCTID_SEQ),
    CONSTRAINT FK_REVIEW_USERID_SEQ FOREIGN KEY (USERID_SEQ) REFERENCES "user"(USERID_SEQ),
    CONSTRAINT FK_REVIEW_ORDERITEMID_SEQ FOREIGN KEY (ORDERITEMID_SEQ) REFERENCES ORDERITEM(ORDERITEMID_SEQ)
);

COMMENT ON TABLE REVIEW IS '리뷰 테이블';
COMMENT ON COLUMN REVIEW.REVIEWID_SEQ IS '리뷰고유ID';
COMMENT ON COLUMN REVIEW.POSTID_SEQ IS '게시물ID (FK -> ProductPost)';
COMMENT ON COLUMN REVIEW.PRODUCTID_SEQ IS '상품ID (FK -> Product, nullable)';
COMMENT ON COLUMN REVIEW.USERID_SEQ IS '유저ID (FK -> User)';
COMMENT ON COLUMN REVIEW.ORDERITEMID_SEQ IS '주문상세ID (FK -> OrderItem)';
COMMENT ON COLUMN REVIEW.RATING IS '평점 (1~5점)';
COMMENT ON COLUMN REVIEW.CONTENT IS '리뷰텍스트';
COMMENT ON COLUMN REVIEW.SELLERREPLY IS '판매자 답글';
COMMENT ON COLUMN REVIEW.SELLERREPLYAT IS '판매자 답글 작성일시';
COMMENT ON COLUMN REVIEW.CREATEDAT IS '글쓴날짜';
COMMENT ON COLUMN REVIEW.UPDATEDAT IS '수정한날짜';

-- 리뷰이미지(ReviewImage)
CREATE TABLE REVIEWIMAGE (
    REVIEWIMAGEID_SEQ NUMBER PRIMARY KEY,
    REVIEWID_SEQ NUMBER NOT NULL,
    IMAGEURL VARCHAR2(500) NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REVIEWIMAGE_REVIEWID_SEQ FOREIGN KEY (REVIEWID_SEQ) REFERENCES REVIEW(REVIEWID_SEQ)
);

COMMENT ON TABLE REVIEWIMAGE IS '리뷰이미지 테이블';
COMMENT ON COLUMN REVIEWIMAGE.REVIEWIMAGEID_SEQ IS '리뷰이미지ID';
COMMENT ON COLUMN REVIEWIMAGE.REVIEWID_SEQ IS '리뷰ID (FK -> Review)';
COMMENT ON COLUMN REVIEWIMAGE.IMAGEURL IS '이미지경로';
COMMENT ON COLUMN REVIEWIMAGE.CREATEDAT IS '이미지 업로드 날짜';

-- 환불/교환(Refund)
CREATE TABLE REFUND (
    REFUNDID_SEQ NUMBER PRIMARY KEY,
    ORDERITEMID_SEQ NUMBER NOT NULL,
    USERID_SEQ NUMBER NOT NULL,
    REFUNDTYPE VARCHAR2(3),
    REASON VARCHAR2(100) NOT NULL,
    REASONDETAIL VARCHAR2(2000),
    REFUNDAMOUNT NUMBER,
    STATUS VARCHAR2(20),
    PREVIOUSSTATUS VARCHAR2(20),
    SELLERRESPONSE VARCHAR2(200),
    CREATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REFUND_ORDERITEMID_SEQ FOREIGN KEY (ORDERITEMID_SEQ) REFERENCES ORDERITEM(ORDERITEMID_SEQ),
    CONSTRAINT FK_REFUND_USERID_SEQ FOREIGN KEY (USERID_SEQ) REFERENCES "user"(USERID_SEQ)
);

COMMENT ON TABLE REFUND IS '환불/교환 테이블';
COMMENT ON COLUMN REFUND.REFUNDID_SEQ IS '환불/교환 고유ID';
COMMENT ON COLUMN REFUND.ORDERITEMID_SEQ IS '주문상세ID (FK -> OrderItem)';
COMMENT ON COLUMN REFUND.USERID_SEQ IS '유저ID (FK -> User)';
COMMENT ON COLUMN REFUND.REFUNDTYPE IS '환불/교환 유형 (REF=환불, EXC=교환)';
COMMENT ON COLUMN REFUND.REASON IS '이유 (선택식)';
COMMENT ON COLUMN REFUND.REASONDETAIL IS '이유를 텍스트로';
COMMENT ON COLUMN REFUND.REFUNDAMOUNT IS '환불하는 총가격';
COMMENT ON COLUMN REFUND.STATUS IS '상태 (REQUESTED, APPROVED, REJECTED, COMPLETED)';
COMMENT ON COLUMN REFUND.PREVIOUSSTATUS IS '요청 전 주문상세 상태';
COMMENT ON COLUMN REFUND.SELLERRESPONSE IS '판매자 처리 메모';
COMMENT ON COLUMN REFUND.CREATEDAT IS '환불/교환신청시간';
COMMENT ON COLUMN REFUND.UPDATEDAT IS '상태 변경 시간';

-- ============================================
-- 3. 인덱스 생성 (성능 최적화)
-- ============================================

-- 이메일 인덱스 (로그인 시 사용)
CREATE INDEX IDX_USER_EMAIL ON "user"(EMAIL);

-- 판매자ID 인덱스 (상품게시물 조회 시 사용)
CREATE INDEX IDX_PRODUCTPOST_USERID_SEQ ON PRODUCTPOST(USERID_SEQ);

-- 게시물ID 인덱스 (상품 조회 시 사용)
CREATE INDEX IDX_PRODUCT_POSTID_SEQ ON PRODUCT(POSTID_SEQ);

-- 유저ID 인덱스 (장바구니, 찜 조회 시 사용)
CREATE INDEX IDX_CART_USERID_SEQ ON CART(USERID_SEQ);
CREATE INDEX IDX_WISHLIST_USERID_SEQ ON WISHLIST(USERID_SEQ);
CREATE INDEX IDX_WISHLIST_POSTID_SEQ ON WISHLIST(POSTID_SEQ);

-- 주문번호 인덱스 (주문 조회 시 사용)
CREATE INDEX IDX_ORDER_OD_NO ON "order"(OD_NO);
CREATE INDEX IDX_ORDER_USERID_SEQ ON "order"(USERID_SEQ);

-- 주문상세 인덱스
CREATE INDEX IDX_ORDERITEM_ORDERID_SEQ ON ORDERITEM(ORDERID_SEQ);
CREATE INDEX IDX_ORDERITEM_PRODUCTID_SEQ ON ORDERITEM(PRODUCTID_SEQ);

-- 리뷰 인덱스
CREATE INDEX IDX_REVIEW_POSTID_SEQ ON REVIEW(POSTID_SEQ);
CREATE INDEX IDX_REVIEW_USERID_SEQ ON REVIEW(USERID_SEQ);

-- 환불 인덱스
CREATE INDEX IDX_REFUND_USERID_SEQ ON REFUND(USERID_SEQ);
CREATE INDEX IDX_REFUND_ORDERITEMID_SEQ ON REFUND(ORDERITEMID_SEQ);

-- ============================================
-- 4. 트리거 생성 (시퀀스 자동 증가)
-- ============================================

-- 회원 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_USER_USERID
    BEFORE INSERT ON "user"
    FOR EACH ROW
BEGIN
    IF :NEW.USERID_SEQ IS NULL THEN
        :NEW.USERID_SEQ := SEQ_USER_USERID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 카테고리 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_CATEGORY_CATEGORYID_SEQ
    BEFORE INSERT ON CATEGORY
    FOR EACH ROW
BEGIN
    IF :NEW.CATEGORYID_SEQ IS NULL THEN
        :NEW.CATEGORYID_SEQ := SEQ_CATEGORY_CATEGORYID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 상품게시물 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PRODUCTPOST_POSTID_SEQ
    BEFORE INSERT ON PRODUCTPOST
    FOR EACH ROW
BEGIN
    IF :NEW.POSTID_SEQ IS NULL THEN
        :NEW.POSTID_SEQ := SEQ_PRODUCTPOST_POSTID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 상품 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PRODUCT_PRODUCTID_SEQ
    BEFORE INSERT ON PRODUCT
    FOR EACH ROW
BEGIN
    IF :NEW.PRODUCTID_SEQ IS NULL THEN
        :NEW.PRODUCTID_SEQ := SEQ_PRODUCT_PRODUCTID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 상품이미지 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PRODUCTIMAGE_IMAGEID_SEQ
    BEFORE INSERT ON PRODUCTIMAGE
    FOR EACH ROW
BEGIN
    IF :NEW.IMAGEID_SEQ IS NULL THEN
        :NEW.IMAGEID_SEQ := SEQ_PRODUCTIMAGE_IMAGEID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 장바구니 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_CART_CARTID_SEQ
    BEFORE INSERT ON CART
    FOR EACH ROW
BEGIN
    IF :NEW.CARTID_SEQ IS NULL THEN
        :NEW.CARTID_SEQ := SEQ_CART_CARTID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 찜 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_WISHLIST_WISHLISTID_SEQ
    BEFORE INSERT ON WISHLIST
    FOR EACH ROW
BEGIN
    IF :NEW.WISHLISTID_SEQ IS NULL THEN
        :NEW.WISHLISTID_SEQ := SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 찜수 자동 업데이트 트리거 (WISHLIST INSERT/DELETE 시 PRODUCTPOST.WISHCOUNT 자동 갱신)
CREATE OR REPLACE TRIGGER TRG_UPDATE_WISHCOUNT
    AFTER INSERT OR DELETE ON WISHLIST
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        -- 찜 추가 시: WISHCOUNT +1
        UPDATE PRODUCTPOST SET WISHCOUNT = NVL(WISHCOUNT, 0) + 1 WHERE POSTID_SEQ = :NEW.POSTID_SEQ;
    ELSIF DELETING THEN
        -- 찜 삭제 시: WISHCOUNT -1
        UPDATE PRODUCTPOST SET WISHCOUNT = NVL(WISHCOUNT, 0) - 1 WHERE POSTID_SEQ = :OLD.POSTID_SEQ;
    END IF;
END;
/

-- 주문 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_ORDER_ORDERID_SEQ
    BEFORE INSERT ON "order"
    FOR EACH ROW
BEGIN
    IF :NEW.ORDERID_SEQ IS NULL THEN
        :NEW.ORDERID_SEQ := SEQ_ORDER_ORDERID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 주문상세 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_ORDERITEM_ORDERITEMID_SEQ
    BEFORE INSERT ON ORDERITEM
    FOR EACH ROW
BEGIN
    IF :NEW.ORDERITEMID_SEQ IS NULL THEN
        :NEW.ORDERITEMID_SEQ := SEQ_ORDERITEM_ORDERITEMID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 결제 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_PAYMENT_PAYMENTID
    BEFORE INSERT ON PAYMENT
    FOR EACH ROW
BEGIN
    IF :NEW.PAYMENTID IS NULL THEN
        :NEW.PAYMENTID := SEQ_PAYMENT_PAYMENTID.NEXTVAL;
    END IF;
END;
/

-- 계좌 ID 자동 증가 트리거 제거됨 (ACCOUNT 테이블 미사용)

-- 리뷰 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_REVIEW_REVIEWID_SEQ
    BEFORE INSERT ON REVIEW
    FOR EACH ROW
BEGIN
    IF :NEW.REVIEWID_SEQ IS NULL THEN
        :NEW.REVIEWID_SEQ := SEQ_REVIEW_REVIEWID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 리뷰이미지 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_REVIEWIMAGE_REVIEWIMAGEID_SEQ
    BEFORE INSERT ON REVIEWIMAGE
    FOR EACH ROW
BEGIN
    IF :NEW.REVIEWIMAGEID_SEQ IS NULL THEN
        :NEW.REVIEWIMAGEID_SEQ := SEQ_REVIEWIMAGE_REVIEWIMAGEID_SEQ.NEXTVAL;
    END IF;
END;
/

-- 환불/교환 ID 자동 증가 트리거
CREATE OR REPLACE TRIGGER TRG_REFUND_REFUNDID_SEQ
    BEFORE INSERT ON REFUND
    FOR EACH ROW
BEGIN
    IF :NEW.REFUNDID_SEQ IS NULL THEN
        :NEW.REFUNDID_SEQ := SEQ_REFUND_REFUNDID_SEQ.NEXTVAL;
    END IF;
END;
/

-- ============================================
-- 4. 테스트 데이터 삽입
-- ============================================

-- 테스트 사용자 데이터 삽입
-- LoginForm.jsx에서 사용하는 seller@dansungsa.com 계정과 일치하도록 설정

-- 판매자 계정
-- 주의: 이미 데이터가 있는 경우 중복 방지를 위해 조건부 삽입 사용 권장
INSERT INTO "user" (
    USERID_SEQ,
    EMAIL,
    PASSWORD,
    NAME,
    PHONE,
    ZIPCODE,
    ISSELLER,
    BN_NO,
    BRAND,
    CREATEDAT,
    UPDATEDAT,
    D_ADDR,
    ADDR
) 
SELECT 
    SEQ_USER_USERID_SEQ.NEXTVAL,
    'seller@dansungsa.com',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',  -- BCrypt 암호화된 'password123'
    '단성사 판매자',
    '010-1234-5678',
    '03123',
    1,  -- 판매자 (1: 사업자)
    '123-45-67890',
    '단성사',
    SYSTIMESTAMP,
    SYSTIMESTAMP,
    '123',
    '서울특별시 종로구 종로'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM "user" WHERE EMAIL = 'seller@dansungsa.com');

-- 일반 회원 계정
INSERT INTO "user" (
    USERID_SEQ,
    EMAIL,
    PASSWORD,
    NAME,
    PHONE,
    ZIPCODE,
    ISSELLER,
    CREATEDAT,
    UPDATEDAT,
    D_ADDR,
    ADDR
) 
SELECT 
    SEQ_USER_USERID_SEQ.NEXTVAL,
    'user@dansungsa.com',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',  -- BCrypt 암호화된 'password123'
    '일반 회원',
    '010-9876-5432',
    '06141',
    0,  -- 일반 회원 (0: 일반)
    SYSTIMESTAMP,
    SYSTIMESTAMP,
    '456',
    '서울특별시 강남구 테헤란로'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM "user" WHERE EMAIL = 'user@dansungsa.com');

-- WISHLIST 테스트 데이터 삽입
-- 인기순 테스트를 위한 찜 데이터 생성
-- 주의: POSTID_SEQ와 USERID_SEQ가 실제로 존재하는 경우에만 실행
-- 게시물 9번 (POSTID_SEQ 9) - 가장 인기: 5명이 찜
INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 3, 9, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 9) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 3)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 3 AND POSTID_SEQ = 9);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 4, 9, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 9) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 4)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 4 AND POSTID_SEQ = 9);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 5, 9, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 9) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 5)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 5 AND POSTID_SEQ = 9);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 6, 9, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 9) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 6)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 6 AND POSTID_SEQ = 9);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 7, 9, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 9) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 7)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 7 AND POSTID_SEQ = 9);

-- 게시물 10번 (POSTID_SEQ 10) - 중간 인기: 3명이 찜
INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 3, 10, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 10) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 3)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 3 AND POSTID_SEQ = 10);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 4, 10, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 10) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 4)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 4 AND POSTID_SEQ = 10);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 5, 10, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 10) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 5)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 5 AND POSTID_SEQ = 10);

-- 게시물 11번 (POSTID_SEQ 11) - 높은 인기: 4명이 찜
INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 3, 11, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 11) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 3)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 3 AND POSTID_SEQ = 11);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 4, 11, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 11) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 4)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 4 AND POSTID_SEQ = 11);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 6, 11, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 11) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 6)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 6 AND POSTID_SEQ = 11);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 7, 11, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 11) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 7)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 7 AND POSTID_SEQ = 11);

-- 게시물 12번 (POSTID_SEQ 12) - 낮은 인기: 2명이 찜
INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 3, 12, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 12) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 3)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 3 AND POSTID_SEQ = 12);

INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 5, 12, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 12) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 5)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 5 AND POSTID_SEQ = 12);

-- 게시물 13번 (POSTID_SEQ 13) - 매우 낮은 인기: 1명만 찜
INSERT INTO WISHLIST (WISHLISTID_SEQ, USERID_SEQ, POSTID_SEQ, CREATEDAT) 
SELECT SEQ_WISHLIST_WISHLISTID_SEQ.NEXTVAL, 4, 13, SYSTIMESTAMP FROM DUAL
WHERE EXISTS (SELECT 1 FROM PRODUCTPOST WHERE POSTID_SEQ = 13) 
  AND EXISTS (SELECT 1 FROM "user" WHERE USERID_SEQ = 4)
  AND NOT EXISTS (SELECT 1 FROM WISHLIST WHERE USERID_SEQ = 4 AND POSTID_SEQ = 13);

-- 게시물 14번 (POSTID 14) - 찜 없음: 0명 (인기순에서 가장 낮음)

-- ============================================
-- 완료 메시지
-- ============================================
SELECT 'Oracle DB 스키마 생성이 완료되었습니다!' AS MESSAGE FROM DUAL;


